### ISSUE TITLE
battery Widget non functioning

### ISSUE THREAD

**Issue by jimmy6616** [neuhausj/Ethos-resources#1]
Frsky x20S running 1.5.17 , battery shows 100V and 95% when the actual readings should be 23.74v @ 70%

**Comment by neuhausj** [comment]
I'll have a look. Which cell settings did you use ?
Did you test it with 1.5.15 as well, to check if it is an issue linked to 1.5.17 ?

**Comment by jimmy6616** [comment]
Never tested with .15. Widget battery, sensor VFAS which is pack voltage. Min V 3.5 , Max V 4.2
Jim 




On Friday, October 18, 2024, 10:33 AM, neuhausj ***@***.***> wrote:




I'll have a look. Which cell settings did you use ?
Did you test it with 1.5.15 as well, to check if it is an issue linked to 1.5.17 ?

**Comment by neuhausj** [comment]
I don't have any VFAS sensor to test, but I tried to simulate the issue by forcing the value to 25.74V.
However it is still displayed correctly in the simulator:
![image](https://github.com/user-attachments/assets/8f8d7781-bc3b-464f-a41f-6f04dad33d32)

(or cell display >)
![image](https://github.com/user-attachments/assets/5f9c4d00-2ea0-4abf-8e0e-7b4232419c1f)


Could you take a screenshot from the telemetry sensor available and its option? 
Do you have another option available as voltage source?

**Comment by jimmy6616** [comment]
Sorry only the VFAS sensor , it may well be 1.5.17 causing the issue. I have attached my screenshots 
![IMG_1440](https://github.com/user-attachments/assets/7c4576d6-92d6-461b-9de7-c113cc34f9a5)
![IMG_1439](https://github.com/user-attachments/assets/b39593d9-7afd-4a00-b587-0c0bef3acdbb)
![IMG_1438](https://github.com/user-attachments/assets/68ca6476-c392-4c8c-b822-6770068ea98b)

**Comment by neuhausj** [comment]
Could you try to reduce the number of decimals to 1 in your sensor setting?
Is the voltage correctly displayed in a "Value" widget ?

I tried on my radio but it still looked ok with 1 or 2 decimals (on 1.5.15 with a X20Pro though).
![image](https://github.com/user-attachments/assets/84938663-74a4-4a52-96e2-55e369f70dbd)

**Comment by jimmy6616** [comment]
The issue has been found. On Ethos 1.5.17 there are 2 entries marked Telemetry, one should actually say Telemetry Status , I had the wrong one selected. All good and sorry for the confusion and trouble 




On Friday, October 18, 2024, 1:34 PM, neuhausj ***@***.***> wrote:




Could you try to reduce the number of decimals to 1 in your sensor setting?
Is the voltage correctly displayed in a "Value" widget ?

I tried on my radio but it still looked ok (on 1.5.15 with a X20Pro though).
image.png (view on web)

**Comment by neuhausj** [comment]
No worries, I also saw the 2 Telemetry in the simulator which is kind of confusing.
Nice if it works now ! ;)
